### ISSUE TITLE
Widgets

### ISSUE THREAD

**Issue by iMario97** [sammwyy/awesome-twitch#1]
En la sección de Widgets, Show Emote redirige a **https://github.com/sammwyy/awesome-twitch/blob/main/show-emote.sammwy.com**
Esto pasa porque te olvidaste de poner **https://**
![image](https://user-images.githubusercontent.com/54608092/193427571-abbe0a90-b790-468f-81e6-59305128e459.png)
![image](https://user-images.githubusercontent.com/54608092/193427616-b9aa27cd-b0f1-433b-bfce-9ff0d83bab1a.png)
![image](https://user-images.githubusercontent.com/54608092/193427628-b49bf992-7c85-4ac4-8681-6d8a2e2888a6.png)

**Comment by sammwyy** [comment]
Ya está arreglado, gracias por avisar :)
